basePath: /
host: localhost:8080
info:
  contact:
    name: Lavish Goyal
  description: A Golang application to test Devops and Backend concepts
  license:
    name: MIT
  title: The Image Uploader App
  version: "1.0"
paths:
  /health:
    get:
      consumes:
      - '*/*'
      description: get the status of server.
      produces:
      - text/plain
      responses:
        "200":
          description: OK
      summary: Show the status of server.
      tags:
      - health
swagger: "2.0"
